package handler

import (
	"encoding/json"
	"net/http"
	"os"
	"path/filepath"
)

const sbomSummaryFile = "data/sbom/summary.json"

// HandleSbom returns the SBOM summary (component counts + severity tallies
// per Podman profile) generated by cmd/sbomgen.
func HandleSbom(w http.ResponseWriter, r *http.Request) {
	home, err := os.UserHomeDir()
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": "cannot determine home dir"})
		return
	}
	path := filepath.Join(home, "Github", "nightforge", sbomSummaryFile)
	data, err := os.ReadFile(path)
	if err != nil {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		json.NewEncoder(w).Encode(map[string]string{"error": "no SBOM data yet — run cmd/sbomgen"}) //nolint:errcheck
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write(data) //nolint:errcheck
}
