#!/usr/bin/env python3
"""cue-to-kdl.py — generate Niri KDL from the NightForge CUE config.

Phase 3 of the CUE migration: CUE data is the source of truth for the
structured sections (spawn-at-startup, keybinds, window-rules) and this
generator renders them back to KDL into a staging config tree. The staging
tree additionally includes the static KDL sections (input, compositor,
colors, layout) copied verbatim from dotfiles so behavior is preserved.

Usage:
  scripts/cue-to-kdl.py [--staging DIR]   (default DIR: build/niri-staging/)

Exits 0 on success. Generated tree layout:
  build/niri-staging/
    config.kdl                 (spawn-at-startup + includes)
    includes/keybinds.kdl      (generated from CUE)
    includes/window-rules.kdl  (generated from CUE)
    includes/{input,compositor,colors}.kdl  (copied verbatim)
"""

import json
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CUE_DIR = REPO_ROOT / "cue"
SRC_INCLUDES = REPO_ROOT / "dotfiles" / "niri" / ".config" / "niri" / "includes"
STATIC_INCLUDES = ("input.kdl", "compositor.kdl", "colors.kdl")


def q(s: str) -> str:
    """KDL string literal (double-quoted)."""
    return '"' + s.replace('"', '\\"') + '"'


def export_config() -> dict:
    out = subprocess.run(
        ["cue", "export", ".", "--out", "json"],
        cwd=CUE_DIR, capture_output=True, text=True, check=True,
    ).stdout
    return json.loads(out)["config"]


def render_spawns(spawns: list) -> list[str]:
    return [f'spawn-at-startup {" ".join(q(a) for a in s["argv"])}' for s in spawns]


def render_bind(b: dict) -> str:
    a = b["action"]
    if a["kind"] == "spawn":
        action = 'spawn ' + ' '.join(q(t) for t in a["argv"])
    else:
        action = a["name"] + (f' {q(a["arg"])}' if a.get("arg") is not None else "")
    flags = []
    if b.get("allowWhenLocked"):
        flags.append("allow-when-locked=true")
    if b.get("repeat") is False:
        flags.append("repeat=false")
    if b.get("hotkeyOverlayTitle"):
        flags.append(f'hotkey-overlay-title={q(b["hotkeyOverlayTitle"])}')
    head = b["combo"] + (" " + " ".join(flags) if flags else "")
    return f"    {head} {{ {action}; }}"


def render_keybinds(binds: list) -> str:
    out = ["// Generated by cue-to-kdl.py from cue/nightforge.cue — do not edit by hand.",
           "// Mod = Super (Windows key)", "", "binds {"]
    out.extend(render_bind(b) for b in binds)
    out.append("}")
    return "\n".join(out) + "\n"


def render_match(regex: str) -> str:
    return f'r#"{regex}"#'


def render_width(w: dict) -> str:
    if "proportion" in w:
        return f"{{ proportion {w['proportion']}; }}"
    return f"{{ fixed {w['fixed']}; }}"


def render_rule(r: dict) -> str:
    lines = ["window-rule {"]
    clauses = []
    if r.get("appId"):
        clauses.append(f"app-id={render_match(r['appId'])}")
    if r.get("title"):
        clauses.append(f"title={render_match(r['title'])}")
    if clauses:
        lines.append("    match " + " ".join(clauses))
    props = [
        ("geometry-corner-radius", r.get("geometryCornerRadius")),
        ("clip-to-geometry", r.get("clipToGeometry")),
        ("open-floating", r.get("openFloating")),
        ("open-fullscreen", r.get("openFullscreen")),
        ("opacity", r.get("opacity")),
        ("max-width", r.get("maxWidth")),
        ("max-height", r.get("maxHeight")),
        ("block-out-from", r.get("blockOutFrom")),
    ]
    for name, v in props:
        if v is None:
            continue
        if isinstance(v, bool):
            lines.append(f"    {name} {'true' if v else 'false'}")
        elif isinstance(v, str):
            lines.append(f"    {name} {q(v)}")
        else:
            lines.append(f"    {name} {v}")
    if r.get("defaultColumnWidth"):
        lines.append(f"    default-column-width {render_width(r['defaultColumnWidth'])}")
    if r.get("defaultWindowHeight"):
        lines.append(f"    default-window-height {render_width(r['defaultWindowHeight'])}")
    lines.append("}")
    return "\n".join(lines)


def render_window_rules(rules: list) -> str:
    out = ["// Generated by cue-to-kdl.py from cue/nightforge.cue — do not edit by hand.", ""]
    out.append("\n\n".join(render_rule(r) for r in rules))
    return "\n".join(out) + "\n"


def main() -> int:
    staging = REPO_ROOT / "build" / "niri-staging"
    if "--staging" in sys.argv:
        staging = Path(sys.argv[sys.argv.index("--staging") + 1]).resolve()
    elif "--help" in sys.argv or "-h" in sys.argv:
        print(__doc__)
        return 0

    cfg = export_config()

    includes_dir = staging / "includes"
    includes_dir.mkdir(parents=True, exist_ok=True)

    # Static includes copied verbatim (behavior preservation).
    for name in STATIC_INCLUDES:
        shutil.copy2(SRC_INCLUDES / name, includes_dir / name)

    (includes_dir / "keybinds.kdl").write_text(render_keybinds(cfg["binds"]))
    (includes_dir / "window-rules.kdl").write_text(render_window_rules(cfg["windowRules"]))

    spawn_lines = render_spawns(cfg["spawnAtStartup"])
    config_kdl = "\n".join([
        "// Niri Configuration — NightForge Operator Workstation (CUE-generated)",
        "// Generated by cue-to-kdl.py from cue/nightforge.cue — do not edit by hand.",
        "// Static sections (input/compositor/colors) preserved verbatim.",
        "",
        *spawn_lines,
        "",
        'include "includes/input.kdl"',
        'include "includes/keybinds.kdl"',
        'include "includes/window-rules.kdl"',
        'include "includes/compositor.kdl"',
        'include "includes/colors.kdl"',
        "",
    ])
    (staging / "config.kdl").write_text(config_kdl)

    print(f"Generated staging config at {staging}")
    print(f"  spawn-at-startup: {len(cfg['spawnAtStartup'])}")
    print(f"  binds:            {len(cfg['binds'])}")
    print(f"  window-rules:     {len(cfg['windowRules'])}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
