// cue-to-kdl — generate Niri KDL from the NightForge CUE config.
//
// Go port of scripts/cue-to-kdl.py (S187). Same inputs, same staging tree,
// same exit codes. The only intentional output difference is the generator
// name in generated-file comments (".py" removed).
//
// CUE data is the source of truth for the structured sections
// (spawn-at-startup, keybinds, window-rules); this generator renders them
// back to KDL into a staging config tree. The staging tree additionally
// includes the static KDL sections (input, compositor, colors) copied
// verbatim from dotfiles so behavior is preserved.
//
// Usage:
//
//	cue-to-kdl [--staging DIR]   (default DIR: build/niri-staging/)
//
// Exits 0 on success. Generated tree layout:
//
//	build/niri-staging/
//	  config.kdl                 (spawn-at-startup + includes)
//	  includes/keybinds.kdl      (generated from CUE)
//	  includes/window-rules.kdl  (generated from CUE)
//	  includes/{input,compositor,colors}.kdl  (copied verbatim)
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/ForeverLX/nightforge/internal/nfutil"
)

const usage = `cue-to-kdl — generate Niri KDL from the NightForge CUE config.

Phase 3 of the CUE migration: CUE data is the source of truth for the
structured sections (spawn-at-startup, keybinds, window-rules) and this
generator renders them back to KDL into a staging config tree. The staging
tree additionally includes the static KDL sections (input, compositor,
colors, layout) copied verbatim from dotfiles so behavior is preserved.

Usage:
  cue-to-kdl [--staging DIR]   (default DIR: build/niri-staging/)

Exits 0 on success. Generated tree layout:
  build/niri-staging/
    config.kdl                 (spawn-at-startup + includes)
    includes/keybinds.kdl      (generated from CUE)
    includes/window-rules.kdl  (generated from CUE)
    includes/{input,compositor,colors}.kdl  (copied verbatim)
`

// q renders a KDL string literal (double-quoted, escaped).
func q(s string) string { return `"` + strings.ReplaceAll(s, `"`, `\"`) + `"` }

// numStr renders an exported CUE number exactly as Python rendered the
// json.loads value: integer literals print verbatim ("8"), float literals
// print as Python's str(float) ("0.90" -> "0.9", "0.0" -> "0.0").
func numStr(n json.Number) string {
	s := n.String()
	if !strings.ContainsAny(s, ".eE") {
		return s
	}
	f, err := n.Float64()
	if err != nil {
		return s
	}
	if math.Trunc(f) == f && math.Abs(f) < 1e16 {
		return strconv.FormatFloat(f, 'f', 1, 64)
	}
	return strconv.FormatFloat(f, 'g', -1, 64)
}

func renderSpawns(spawns []nfutil.Spawn) []string {
	out := make([]string, 0, len(spawns))
	for _, s := range spawns {
		args := make([]string, len(s.Argv))
		for i, a := range s.Argv {
			args[i] = q(a)
		}
		out = append(out, "spawn-at-startup "+strings.Join(args, " "))
	}
	return out
}

func renderBind(b nfutil.Bind) string {
	a := b.Action
	var action string
	if a.Kind == "spawn" {
		args := make([]string, len(a.Argv))
		for i, t := range a.Argv {
			args[i] = q(t)
		}
		action = "spawn " + strings.Join(args, " ")
	} else {
		action = a.Name
		if a.Arg != nil {
			action += " " + q(*a.Arg)
		}
	}
	var flags []string
	if b.AllowWhenLocked != nil && *b.AllowWhenLocked {
		flags = append(flags, "allow-when-locked=true")
	}
	if b.Repeat != nil && !*b.Repeat {
		flags = append(flags, "repeat=false")
	}
	if b.HotkeyOverlayTitle != nil {
		flags = append(flags, "hotkey-overlay-title="+q(*b.HotkeyOverlayTitle))
	}
	head := b.Combo
	if len(flags) > 0 {
		head += " " + strings.Join(flags, " ")
	}
	return fmt.Sprintf("    %s { %s; }", head, action)
}

func renderKeybinds(binds []nfutil.Bind) string {
	lines := []string{
		"// Generated by cue-to-kdl from cue/nightforge.cue — do not edit by hand.",
		"// Mod = Super (Windows key)",
		"",
		"binds {",
	}
	for _, b := range binds {
		lines = append(lines, renderBind(b))
	}
	lines = append(lines, "}")
	return strings.Join(lines, "\n") + "\n"
}

func renderMatch(regex string) string { return `r#"` + regex + `"#` }

func renderWidth(w nfutil.Width) string {
	if w.Proportion != nil {
		return fmt.Sprintf("{ proportion %s; }", numStr(*w.Proportion))
	}
	return fmt.Sprintf("{ fixed %s; }", numStr(*w.Fixed))
}

func renderRule(r nfutil.Rule) string {
	lines := []string{"window-rule {"}
	var clauses []string
	if r.AppID != nil {
		clauses = append(clauses, "app-id="+renderMatch(*r.AppID))
	}
	if r.Title != nil {
		clauses = append(clauses, "title="+renderMatch(*r.Title))
	}
	if len(clauses) > 0 {
		lines = append(lines, "    match "+strings.Join(clauses, " "))
	}
	props := []struct {
		name string
		v    any
	}{
		{"geometry-corner-radius", r.GeometryCornerRadius},
		{"clip-to-geometry", r.ClipToGeometry},
		{"open-floating", r.OpenFloating},
		{"open-fullscreen", r.OpenFullscreen},
		{"opacity", r.Opacity},
		{"max-width", r.MaxWidth},
		{"max-height", r.MaxHeight},
		{"block-out-from", r.BlockOutFrom},
	}
	for _, p := range props {
		switch v := p.v.(type) {
		case *bool:
			if v == nil {
				continue
			}
			if *v {
				lines = append(lines, "    "+p.name+" true")
			} else {
				lines = append(lines, "    "+p.name+" false")
			}
		case *string:
			if v == nil {
				continue
			}
			lines = append(lines, "    "+p.name+" "+q(*v))
		case *json.Number:
			if v == nil {
				continue
			}
			lines = append(lines, "    "+p.name+" "+numStr(*v))
		}
	}
	if r.DefaultColumnWidth != nil {
		lines = append(lines, "    default-column-width "+renderWidth(*r.DefaultColumnWidth))
	}
	if r.DefaultWindowHeight != nil {
		lines = append(lines, "    default-window-height "+renderWidth(*r.DefaultWindowHeight))
	}
	lines = append(lines, "}")
	return strings.Join(lines, "\n")
}

func renderWindowRules(rules []nfutil.Rule) string {
	lines := []string{
		"// Generated by cue-to-kdl from cue/nightforge.cue — do not edit by hand.",
		"",
	}
	blocks := make([]string, len(rules))
	for i, r := range rules {
		blocks[i] = renderRule(r)
	}
	lines = append(lines, strings.Join(blocks, "\n\n"))
	return strings.Join(lines, "\n") + "\n"
}

func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	fi, err := in.Stat()
	if err != nil {
		return err
	}
	out, err := os.OpenFile(dst, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, fi.Mode().Perm())
	if err != nil {
		return err
	}
	defer out.Close()
	if _, err := io.Copy(out, in); err != nil {
		return err
	}
	return out.Close()
}

func run() error {
	root, err := nfutil.RepoRoot()
	if err != nil {
		return err
	}

	// Faithful CLI behavior: --staging wins over --help (as in the Python
	// original's if/elif), a bare --staging is an error, unknown args ignored.
	staging := filepath.Join(root, "build", "niri-staging")
	stagingSet := false
	help := false
	args := os.Args[1:]
	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "--staging":
			if i+1 >= len(args) {
				return fmt.Errorf("--staging requires a directory argument")
			}
			abs, err := filepath.Abs(args[i+1])
			if err != nil {
				return err
			}
			staging = abs
			stagingSet = true
			i++
		case "--help", "-h":
			help = true
		}
	}
	if help && !stagingSet {
		fmt.Print(usage)
		return nil
	}

	cfg, err := nfutil.ExportConfig(root)
	if err != nil {
		return err
	}

	includesDir := filepath.Join(staging, "includes")
	if err := os.MkdirAll(includesDir, 0o755); err != nil {
		return err
	}

	// Static includes copied verbatim (behavior preservation).
	srcIncludes := filepath.Join(root, "dotfiles", "niri", ".config", "niri", "includes")
	for _, name := range []string{"input.kdl", "compositor.kdl", "colors.kdl"} {
		if err := copyFile(filepath.Join(srcIncludes, name), filepath.Join(includesDir, name)); err != nil {
			return err
		}
	}

	if err := os.WriteFile(filepath.Join(includesDir, "keybinds.kdl"), []byte(renderKeybinds(cfg.Binds)), 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(includesDir, "window-rules.kdl"), []byte(renderWindowRules(cfg.WindowRules)), 0o644); err != nil {
		return err
	}

	spawnLines := renderSpawns(cfg.SpawnAtStartup)
	configKDL := strings.Join([]string{
		"// Niri Configuration — NightForge Operator Workstation (CUE-generated)",
		"// Generated by cue-to-kdl from cue/nightforge.cue — do not edit by hand.",
		"// Static sections (input/compositor/colors) preserved verbatim.",
		"",
		strings.Join(spawnLines, "\n"),
		"",
		`include "includes/input.kdl"`,
		`include "includes/keybinds.kdl"`,
		`include "includes/window-rules.kdl"`,
		`include "includes/compositor.kdl"`,
		`include "includes/colors.kdl"`,
		"",
	}, "\n")
	if err := os.WriteFile(filepath.Join(staging, "config.kdl"), []byte(configKDL), 0o644); err != nil {
		return err
	}

	fmt.Printf("Generated staging config at %s\n", staging)
	fmt.Printf("  spawn-at-startup: %d\n", len(cfg.SpawnAtStartup))
	fmt.Printf("  binds:            %d\n", len(cfg.Binds))
	fmt.Printf("  window-rules:     %d\n", len(cfg.WindowRules))
	return nil
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "cue-to-kdl:", err)
		os.Exit(1)
	}
}
