# Basic colors
foreground              #e4e1e9
background              #131318
selection_foreground    #2e2f42
selection_background    #c5c4dd

# Cursor colors
cursor                  #bfc1ff
cursor_text_color       #282b60

# URL underline color when hovering with mouse
url_color               #e8b9d4

# Kitty window border colors
active_border_color     #bfc1ff
inactive_border_color   #46464f
bell_border_color       #ffb4ab

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #282b60
active_tab_background   #bfc1ff
inactive_tab_foreground #c7c5d0
inactive_tab_background #46464f
tab_bar_background      #131318

# Colors for marks
mark1_foreground #282b60
mark1_background #bfc1ff
mark2_foreground #2e2f42
mark2_background #c5c4dd
mark3_foreground #46263b
mark3_background #e8b9d4

# The 16 terminal colors
# black
color0 #131318
color8 #46464f

# red
color1 #ffb4ab
color9 #ffb4ab

# green
color2  #bfc1ff
color10 #bfc1ff

# yellow
color3  #e8b9d4
color11 #e8b9d4

# blue
color4  #c5c4dd
color12 #c5c4dd

# magenta
color5  #e1e0ff
color13 #e1e0ff

# cyan
color6  #ffd8ed
color14 #ffd8ed

# white
color7  #e4e1e9
color15 #e4e1e9
